### ISSUE TITLE
small typo and thanks!

### ISSUE THREAD

**Issue by cschep** [gphat/feedback#2]
hey! thanks for the brave blogging. I believe in the casting aside of the fear and shit. I found a typo!

in this article: http://onemogin.com/java/gc/java-gc-tuning-for-noobs-1.html

this sentence exists: "GC logging is effectively free and definitely worth what trivial amount of time it ocsts."

should probably be "..costs"

thanks again!

**Comment by gphat** [comment]
No problem homie. Thanks for the kind words and the fix. Shipped!
