### ISSUE TITLE
One Mo' Gin styling disaster

### ISSUE THREAD

**Issue by MisterSquishy** [gphat/feedback#7]
FYI one mo gin seems to have gotten gnarfled somehow... e.g. [here](https://onemogin.com/monitoring/case-method-better-monitoring-for-humans.html):

<img width="1728" alt="CleanShot 2023-11-21 at 16 05 20@2x" src="https://github.com/gphat/feedback/assets/5599894/e608f2d0-5559-428d-919f-9af9b1e6c075">

i cite your articles frequently and this illegible gray-text-on-white-background thing is really undermining my credibility 😂 

btw thanks so much for all the great content on that site 🙏

**Comment by gphat** [comment]
Thanks for flagging, I'll fix it up!

**Comment by gphat** [comment]
This is looking swell on my end.

<img width="925" alt="Screenshot 2023-11-21 at 3 09 42 PM" src="https://github.com/gphat/feedback/assets/45159/ea5763b3-37d1-4b77-8cd9-7487afc34759">

What browser/OS is giving you trouble? That'll narrow it down so I can fix it for ya!

**Comment by gphat** [comment]
Nevermind, I found that it's a darkmode thing!

**Comment by gphat** [comment]
Here we go friend, all fixed up in darkmode:

<img width="1617" alt="Screenshot 2023-11-21 at 3 27 04 PM" src="https://github.com/gphat/feedback/assets/45159/ef246ba8-2e81-473f-b1f2-bf68f400479a">

Thanks a ton for flagging!
